<a href="https://colab.research.google.com/github/syaifuddinzuhri/PCVK_Genap_2022/blob/main/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://drive.google.com/uc?export=view&id=1nGskruGp1bNU0llrM2GY5CgaKHG_lQco" width="100" />
<img src="https://drive.google.com/uc?export=view&id=1itnR7dy-nsjeEeUZI-kYF9B6HYwmf7tt" width="75" />

# **LAPORAN CHALLENGE - PENGOLAHAN CITRA DAN VISI KOMPUTER**


---


**Nama : Mochammad Syaifuddin Zuhri**

**NIM : 1941720013**

**Kelas : TI-3C**

**No. Absen : 12**

---

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import cv2 as cv
from google.colab.patches import cv2_imshow

In [ ]:
# PERKALIAN SAKLAR

# Initial matrik a
matrix_a = [[3,2], [7,2]]

# Initial matrik b
matrix_b = [[1,6], [2,5]]

# Initial matrik hasil
hasil = []

print('== Matrix A ==')
print(np.array(matrix_a))
print("\n== Matrix B ==")
print(np.array(matrix_b))

print("\n== Hasil Perkalian Skalar ==")
for x in range(0, len(matrix_a)):
  row = []
  for y in range(0, len(matrix_b)):
    temp = matrix_a[x][y] * matrix_b[x][y] 
    row.append(temp)
  hasil.append(row)

print(np.array(hasil))

== Matrix A ==
[[3 2]
 [7 2]]

== Matrix B ==
[[1 6]
 [2 5]]

== Hasil Perkalian Skalar ==
[[ 3 12]
 [14 10]]


In [ ]:
# PERKALIAN MATRIK

# Initial matrik a
matrix_a = [[3, 5, 6], [1, 5, 2], [8, 7, 5]]

# Initial matrik b
matrix_b = [[5, 1, 4], [5, 3, 5], [5, 3, 9]]

# Initial matrik hasil
hasil = []

# Menghitung perkalian matrik
for x in range(0, len(matrix_a)):
    row = []
    for y in range(0, len(matrix_a[0])):
        total = 0
        for z in range(0, len(matrix_a)):
            total += (matrix_a[x][z] * matrix_b[z][y])
        row.append(total)
    hasil.append(row)

print("\n== Matrik A ==")
print(np.array(matrix_a))

print("\n== Matrik B ==")
print(np.array(matrix_b))

print("\n== Hasil Perkalian Matrik ==")
print(np.array(hasil))


== Matrik A ==
[[3 5 6]
 [1 5 2]
 [8 7 5]]

== Matrik B ==
[[5 1 4]
 [5 3 5]
 [5 3 9]]

== Hasil Perkalian Matrik ==
[[ 70  36  91]
 [ 40  22  47]
 [100  44 112]]


In [ ]:
# Membuat fungsi untuk menghitung konvolusi dengan 4 parameter yaitu:
# - image => citra input
# - kernel => input kernel filter matriks array
# - stride => Jumlah pergeseran untuk setiap perhitungan konvolusi
# - padding => Untuk menambahkan jumlah layer baru pada tiap sisi citra input

def convolution2d(image, kernel, stride, padding):
  # Memodifikasi array citra input dengan jumlah padding berdasarkan parameter, 
  # mode = 'constant' dan value dari padding bernilai 0 
  image = np.pad(image, padding, mode='constant', constant_values=0)

  # Menyimpan tinggi dan lebar dari kernel
  h_kernel, w_kernel = kernel.shape

  # Menyimpan tinggi dan lebar dari citra input / image
  h_padded, w_padded = image.shape

  # menghitung kalkulasi dua nilai tinggi dari kernel dan image
  output_height = (h_padded - h_kernel) // stride + 1

  # menghitung kalkulasi dua nilai lebar dari kernel dan image
  output_width = (w_padded - w_kernel) // stride + 1

  # membuat matriks array kosong baru dengan jumlah tinggi dan lebar dari 
  # hasil kalkulasi sebelumnya
  new_image = np.zeros((output_height, output_width)).astype(np.float32)

  # perulangan berdasarkan hasil kalkulasi tinggi
  for y in range(0, output_height):
    # perulangan berdasarkan hasil kalkulasi lebar
    for x in range(0, output_width):
      # memasukkan nilai tinggi dan lebar ke dalam variabel new_image
      new_image[y][x] = np.sum(
          image[y * stride:y * stride + h_kernel, 
          x * stride:x * stride + w_kernel] * kernel).astype(np.float32)

  # Menampilkan hasil akhir gambar
  print('Pixel ASLI')
  printPixel(image)
  print('\n\nHASIL PERKALIAN')
  printPixel(new_image)

# membuat fungsi proses image
def proccessImage():
  original_img = cv.imread('/content/drive/MyDrive/PCVK/week_3/mandrill.tiff')
  resize_img = cv.resize(original_img, (0,0), fx=0.5, fy=0.5)
  img_gray = cv.cvtColor(resize_img, cv.COLOR_BGR2GRAY)
  return img_gray

# Fungsi menampilkan pixel
def printPixel(img):
  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        print(img[i,j], end = "\t")
    print("\t")

kernel_sharpen = np.array([[1,0,0],
                           [0,1,0],
                           [0,0,1]])

convolution2d(proccessImage(), kernel_sharpen, 1, 0)

Pixel ASLI
105	61	93	51	75	96	104	93	145	84	67	76	120	119	85	141	95	132	83	117	47	137	114	109	136	84	110	142	123	163	128	160	148	113	176	125	80	116	115	83	171	102	64	91	95	187	98	50	87	107	99	119	109	102	147	133	138	163	131	109	127	159	183	153	153	151	138	150	80	88	136	163	142	127	155	64	93	95	104	82	82	103	144	94	88	74	137	102	115	135	168	146	81	101	122	95	162	122	131	178	168	131	125	141	130	96	157	113	64	130	152	188	122	145	72	52	136	129	149	173	119	115	82	105	142	152	106	87	96	90	80	127	126	111	169	80	106	157	178	101	100	106	177	175	164	131	127	146	154	102	80	142	104	127	136	145	163	134	156	154	132	139	187	148	116	105	142	125	129	121	96	106	145	105	126	147	105	136	68	112	136	101	131	136	119	142	159	127	98	140	80	65	114	190	129	179	153	162	137	165	151	103	128	150	170	117	143	124	113	137	87	151	99	84	92	109	178	170	165	153	151	151	149	198	186	162	129	109	137	196	173	126	153	148	160	157	161	170	125	146	148	140	129	148	170	176	181	116	108	69	84	112	117	85	124	151		
99	59	90	52	93	55	49	