<a href="https://colab.research.google.com/github/syaifuddinzuhri/PCVK_Genap_2022/blob/main/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

In [41]:
# PERKALIAN SAKLAR

# Initial matrik a
matrix_a = [[3,2], [7,2]]

# Initial matrik b
matrix_b = [[1,6], [2,5]]

# Initial matrik hasil
hasil = []

print('== Matrix A ==')
print(np.array(matrix_a))
print("\n== Matrix B ==")
print(np.array(matrix_b))

print("\n== Hasil Perkalian Skalar ==")
for x in range(0, len(matrix_a)):
  row = []
  for y in range(0, len(matrix_b)):
    temp = matrix_a[x][y] * matrix_b[x][y] 
    row.append(temp)
  hasil.append(row)

print(np.array(hasil))

== Matrix A ==
[[3 2]
 [7 2]]

== Matrix B ==
[[1 6]
 [2 5]]

== Hasil Perkalian Skalar ==
[[ 3 12]
 [14 10]]


In [43]:
# PERKALIAN MATRIK

# Initial matrik a
matrix_a = [[3, 5, 6], [1, 5, 2], [8, 7, 5]]

# Initial matrik b
matrix_b = [[5, 1, 4], [5, 3, 5], [5, 3, 9]]

# Initial matrik hasil
hasil = []

# Menghitung perkalian matrik
for x in range(0, len(matrix_a)):
    row = []
    for y in range(0, len(matrix_a[0])):
        total = 0
        for z in range(0, len(matrix_a)):
            total += (matrix_a[x][z] * matrix_b[z][y])
        row.append(total)
    hasil.append(row)

print("\n== Matrik A ==")
print(np.array(matrix_a))

print("\n== Matrik B ==")
print(np.array(matrix_b))

print("\n== Hasil Perkalian Matrik ==")
print(np.array(hasil))


== Matrik A ==
[[3 5 6]
 [1 5 2]
 [8 7 5]]

== Matrik B ==
[[5 1 4]
 [5 3 5]
 [5 3 9]]

== Hasil Perkalian Matrik ==
[[ 70  36  91]
 [ 40  22  47]
 [100  44 112]]
